# **TASK 1**
Assume, you have been given a tuple.
a_tuple = ("The Institute", ("Best Mystery & Thriller", "The Silent Patient", 68821), 75717,
[1, 2, 3, 400, 5, 6, 7], ("Best Fiction", "The Testaments", 98291))
Write one line of Python code to access and print the value 400.
===================================================================
Output: 400
===================================================================

In [ ]:
a_tuple = ("The Institute", ("Best Mystery & Thriller", "The Silent Patient", 68821), 75717, [1, 2, 3, 400, 5, 6, 7], ("Best Fiction", "The Testaments", 98291))
print(a_tuple[3][3])

400

# **Task 2**
Assume, you have been given a tuple. Write a Python program that creates a new
tuple excluding the first and last two elements of the given tuple and prints the new tuple.
Hint: You may use tuple slicing.
===================================================================
Sample Input 1:
(10, 20, 24, 25, 26, 35, 70)
Sample Output 1:
(24, 25, 26)
===================================================================
Sample Input 2:
(-10, 20, 30, 40)
Sample Output 2:
()
===================================================================
Sample Input 3:
(-10, 20, 25, 30, 40)

In [ ]:
tuple_a =(input('enter tuple: '))
tuple_a = tuple_a.strip(' () ')
tuple_b = tuple_a.split(', ')
tuple_d = ()
for itaretion in range(len(tuple_b)):
    tuple_b[itaretion] = int(tuple_b[itaretion])
tuple_c = tuple(tuple_b)

if len(tuple_c) >= 4:
    tuple_d = tuple_c[2 : -2]
    print(tuple_d)
else:
    print('Not possible')

enter tuple: (-10, 20, 30, 40)
()

# **TASK 3** 
 Assume, you have been given a tuple.
book_info = (
("Best Mystery & Thriller","The Silent Patient",68,821),
("Best Horror","The Institute",75,717),
("Best History & Biography","The five",31,783 ),
("Best Fiction","The Testaments",98,291)
)
Write a Python program that prints the size of the tuple and all its elements as shown below.
===================================================================
Output:
Size of the tuple is: 4
('Best Mystery & Thriller', 'The Silent Patient', 68, 821)
('Best Horror', 'The Institute', 75, 717)
('Best History & Biography', 'The five', 31, 783)
('Best Fiction', 'The Testaments', 98, 291)
===================================================================

In [ ]:
book_info = ( ("Best Mystery & Thriller","The Silent Patient",68,821), ("Best Horror","The Institute",75,717), ("Best History & Biography","The five",31,783 ), ("Best Fiction","The Testaments",98,291) )
print('Size of the tuple is',len(book_info))
for itaretion in book_info:
    print(itaretion)

Size of the tuple is 4
('Best Mystery & Thriller', 'The Silent Patient', 68, 821)
('Best Horror', 'The Institute', 75, 717)
('Best History & Biography', 'The five', 31, 783)
('Best Fiction', 'The Testaments', 98, 291)

# **Task 4**
Assume, you have been given a tuple with details about books that won the Good Reads
Choice Awards.
book_info = (
("Best Mystery & Thriller","The Silent Patient",68821),
("Best Horror","The Institute",75717),
("Best History & Biography","The five",31783 ),
("Best Fiction","The Testaments",98291)
)
Write a Python program that prints the award category, the book name, and its total votes
earned as shown below.
[Must use Tuple unpacking for printing and need to handle the quotation marks as a part
of the output]
===================================================================
Output:
The Silent Patient won the 'Best Mystery & Thriller' category with 68821 votes
The Institute won the 'Best Horror' category with 75717 votes

The five won the 'Best History & Biography' category with 31783 votes
The Testaments won the 'Best Fiction' category with 98291 votes
===================================================================

In [ ]:
book_info = ( ("Best Mystery & Thriller","The Silent Patient",68821), ("Best Horror","The Institute",75717), ("Best History & Biography","The five",31783 ), ("Best Fiction","The Testaments",98291) )
for itaretion in book_info:
    catagory, book_name, votes = itaretion
    print(f"{book_name} won the '{catagory}' category with {votes} votes")

The Silent Patient won the 'Best Mystery & Thriller' category with 68821 votes
The Institute won the 'Best Horror' category with 75717 votes
The five won the 'Best History & Biography' category with 31783 votes
The Testaments won the 'Best Fiction' category with 98291 votes

# ***TASK 5 ***
Write a python program that takes an input from the user and finds the number of times that the
input is present in a given tuple.
===================================================================
Example 1:
Given tuple: (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
Sample Input 1:
8
Sample Output 1:
8 appears 4 times in the tuple
===================================================================
Example 2
Given tuple: (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
Sample Input 2:
1
Sample Output 2:
1 appears 0 times in the tuple
===================================================================

In [ ]:
tuple_a =(input('enter tuple: '))
elem = int(input('enter element: '))
sum = 0
tuple_a = tuple_a.strip(' () ')
tuple_b = tuple_a.split(', ')
tuple_d = ()
for itaretion in range(len(tuple_b)):
    tuple_b[itaretion] = int(tuple_b[itaretion])
tuple_c = tuple(tuple_b)
for itaretion in tuple_c :
    if elem == itaretion:
          sum = sum + 1
print(elem, 'apears', sum, 'times in the tuple')

enter tuple: (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
enter element: 1
1 apears 0 times in the tuple

# **TASK 6**
Write a Python program to reverse a given tuple.
[You are not allowed to use tuple slicing]
===================================================================
Note: Unlike lists, tuples are immutable. So, in order to reverse a tuple, we may need to convert
it into a list first, then modify the list, and finally convert it back to a tuple.
===================================================================
Example 1:
Given tuple: ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
Output:
('h', 'g', 'f', 'e', 'd', 'c', 'b', 'a')

===================================================================
Example 2:
Given tuple: (10, 20, 30, 40, 50, 60)
Output:
(60, 50, 40, 30, 20, 10)
===================================================================

In [ ]:
tuple_a = ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
list(tuple_a)
list_b = []
for itaretion in range(-1, -1*len(tuple_a) - 1, -1):
   list_b.append(tuple_a[itaretion])
tuple_c = tuple(list_b)
print(tuple_c)

('h', 'g', 'f', 'e', 'd', 'c', 'b', 'a')

In [ ]:
tuple_a = (10, 20, 30, 40, 50, 60)
list(tuple_a)
list_b = []
for itaretion in range(-1, -1*len(tuple_a) - 1, -1):
   list_b.append(tuple_a[itaretion])
tuple_c = tuple(list_b)
print(tuple_c)

(60, 50, 40, 30, 20, 10)

# **TASK 7**
Suppose you are given two dictionaries.
Now create a new dictionary "marks", merging the two dictionaries, so that the original two
dictionaries remain unchanged.
Note: You can use dictionary functions.
===================================================================
Given:
{'Harry':15, 'Draco':8, 'Nevil':19}
{'Ginie':18, 'Luna': 14}
Output:
{'Harry': 15, 'Draco': 8, 'Nevil': 19, 'Ginie': 18, 'Luna': 14}
===================================================================
Given:
{'A':90, 'B': 0}
{'C':50}
Output:
{'A': 90, 'B': 0, 'C': 50}
===================================================================

In [ ]:
dict_a = {'Harry':15, 'Draco':8, 'Nevil':19}
dict_b =  {'Ginie':18, 'Luna': 14}
dict_c = {}
dict_c.update(dict_a)
dict_c.update(dict_b)
print(dict_c)

{'Harry': 15, 'Draco': 8, 'Nevil': 19, 'Ginie': 18, 'Luna': 14}

# **TASK 8**
Write a Python program that takes a dictionary as an input from the user and then prints the  average of all the values in the dictionary. 
[You are not allowed to use len() and sum()] 
===================================================================

Hint (1): For taking dictionary input 

Approach (1): For taking dictionary as an input from the user, you may take the whole dictionary  as a string using the input() function. Then you can use the split(), strip() functions and  conditions to get the keys and values from the string. Finally, you can make the dictionary using  the obtained data. 

Approach (2): If the first approach seems too difficult you can create an empty dictionary and  then just run a simple loop. For each iteration ask the user for a key and a value using the  input() function and keep updating the dictionary with the key and value. 


Hint (2): After you have a dictionary, you can use dictionary functions to get all the values from  it, run loop to calculate the sum and the total number of values in the dictionary in order to find  out the average. 
===================================================================

 Sample Input 1: 
 
{'Jon': 100, 'Dan':200, 'Rob':300} 
Sample Output 1: 

Average is 200. 
===================================================================

 Sample Input 2: 

{'Jon': 100, 'Dan':200, 'Rob':30, 'Ned':110} 
Sample Output 2: 

Average is 110. 
===================================================================

In [ ]:
dict_a = {}
quantity = int(input('enter quantity: '))
sum = 0
for itaretion in range(quantity):
    key = input('enter key: ')
    val = int(input('enter value: '))
    dict_a[key] = val
print(dict_a)

list_a = dict_a.values()

for itaretion in list_a:
    sum = sum + itaretion
avg = sum / quantity
print('Average is ', avg)

enter quantity: 3
enter key: Jon
enter value: 100
enter key: Dan
enter value: 200
enter key: Rob
enter value: 300
{'Jon': 100, 'Dan': 200, 'Rob': 300}
Average is  200.0

In [ ]:
dict_a = input('enter the dictionary: ')
dict_b = dict_a.strip(' {} ')
data = dict_b.split(',')
dict_c = {}
sum = 0
for pair_elem in data:
      data_2 = pair_elem.split(':')
      key = data_2[0].strip(" '' ")
      val = int(data_2[1])
      sum = sum + val
      dict_c[key] = val
avg = sum // (len(dict_c))
print(dict_c)
print(avg)

enter the dictionary: {'Jon': 100, 'Dan':200, 'Rob':300}
{'Jon': 100, 'Dan': 200, 'Rob': 300}
200

# **TASK 9**
Suppose there is a dictionary named exam_marks as given below.

exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190} 

Write a Python program that takes an input from the user and creates a new dictionary with only  those elements from 'exam_marks' whose keys have values higher than the user input  (inclusive). 

===================================================================

 Sample Input 1: 

170 

Sample Output 1:

{'Cierra Vega': 175, 'Alden Cantrell': 200, 'Pierre Cox': 190} 

============================================================
Sample Input 2: 

190

Sample Output 2:

In [ ]:
exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}
user_in = int(input('enter the value: '))
dict_a = {}
for key, val in exam_marks.items():
    if user_in <= val:
        dict_a[key] = val
print(dict_a)

enter the value: 190
{'Alden Cantrell': 200, 'Pierre Cox': 190}

# **TASK 10**
Write a Python program that finds the largest value with its key from a given dictionary.

[You are not allowed to use the max() function for this task]
Note: You do not need to take the dictionaries as an input from the user but your code should work for any given dictionary. Also, you need to handle the quotation marks as a part of the
output.

Hint: Think of membership operators (in and not in). You can use dictionary functions to get the
values.

============================================================

Sample 1:

Given:
{'sci fi': 12, 'mystery': 15, 'horror': 8, 'mythology': 10, 'young_adult': 4, 'adventure':14}

Output:

The highest selling book genre is 'mystery' and the number of books sold are 15.

============================================================

Sample 2:

Given:

{'sci fi': 5, 'mystery': 3, 'horror': 14, 'young_adult': 2, 'adventure':9}

Output:

The highest selling book genre is 'horror' and the number of books sold are 14.

============================================================

In [20]:
given = {'sci fi': 12, 'mystery': 15, 'horror': 8, 'mythology': 10, 'young_adult': 4, 'adventure':14}
max_val = False
max_key = False
for key in given:
    if max_val == False or given[key] > max_val:
        max_val = given[key] 
        max_key = key
print(f"The highest selling book genre is '{max_key}' and the number of books sold are {max_val}")

The highest selling book genre is 'mystery' and the number of books sold are 15

# **TASK 11**
Write a Python program that takes a String as an input from the user and counts the frequency of each character using a dictionary. For solving this problem, you may use each character as a key and its frequency as values. [You are not allowed to use the count() function]

Hint: You can create a new dictionary to store the frequencies. You may ignore case for simplicity (i.e. may consider P and p to be the same).

============================================================

Sample Input:
"Python programming is fun"

Sample Output:

{'p': 2, 'y': 1, 't': 1, 'h': 1, 'o': 2, 'n': 3, 'r': 2, 'g': 2, 'a': 1, 'm': 2, 'i': 2, 's': 1, 'f': 1, 'u': 1}

============================================================

In [ ]:
data = input('enter the string: ')
data = data.lower()
ans = {}
for char in data:
    if char != ' ':
        key = char
        if key not in ans:
            ans[key] = 1
        else:
            ans[key] = ans[key] + 1
print(ans)

enter the string: Python programming is fun
{'p': 2, 'y': 1, 't': 1, 'h': 1, 'o': 2, 'n': 3, 'r': 2, 'g': 2, 'a': 1, 'm': 2, 'i': 2, 's': 1, 'f': 1, 'u': 1}

# **TASK 12**
Suppose you are given the following dictionary where the values are lists.

dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}

Write a Python program that counts the total number of items in a dictionary’s values and prints it.

[Without using sum(), len(), count() functions]

Note: Make changes to the above dictionary and see if your code works properly for other dictionaries as well.

============================================================

Output:
9

============================================================

In [ ]:
dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
count = 0
for key, val in dict_1.items():
   for itaretion in val:
      count = count + 1
print(count)

9

# **TASK 13**
Suppose you have been given the following list of tuples.

list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]

Write a Python program that converts this list of tuples into a dictionary and then prints the dictionary.

[You are not allowed to use set]

Hint: Think of membership operators (in and not in).

============================================================

Output:
{'a': [1, 3, 2], 'b': [2, 1], 'c': [1]}

============================================================

In [10]:
list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]
dict_a = {}
for itaretion in list_1:
    key , val = itaretion
    if dict_a.get(key) == None:
        dict_a[key] = []
    dict_a[key].append(val)
print(dict_a)

{'a': [1, 3, 2], 'b': [2, 1], 'c': [1]}

# **TASK 14**

In [ ]:
var1 = var2 = var3 = var4 = var5 = var6 = False
result1 = result2 = result3 = result4 = result5 = result6 = result7 = result8 = result9 = result10 = False
var1 = 4 < 3 - 1
var2 = var1 and False
var3 = False
var4 = True
var5 = False
var6 = var3 and True
result1 = (var1 or var2) and (8 * 10 > 45)
result2 = (var1 or var2) and (result1 and False)
result3 = (var1 and result1) or result2
result4 = (var1 or var2) or ((var3 and var1) and False)
result5 = (var1 and var2) and (result3 or var1)
result6 = ((var3 or var2) and not result5) or True
result7 = (var4 and result1) and ((result1 and False) or True)
result8 = ((var1 and result3) and (var5 or var6)) and True
result9 = ((result2 and var2) or (result7 and var1)) and False
result10 = not(var1 and True)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(result6)
print(result7)
print(result8)
print(result9)
print(result10)

False
False
False
False
False
True
False
False
False
True

# TASk 16

In [ ]:
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 
index1 = 0 
index2 = 0 
index1 = 1 
while(index1<10): 
    myList[index1] = index1+4 
    index2 = 1 
    while(index2<index1):
        myList[index1] = myList[index1] + myList[index2]-index1  
        index2 = index2+1
    print(myList[index1]) 
    index1 = index1+1

5
9
15
25
43
77
143
273
531

# **TASK 17**

In [ ]:
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
index1 = 0
index2 = 0
index1 = 1
while (index1 < 10):
    myList[index1] = index1 + 4
    index2 = 1
    while (index2 < index1):
        myList[index1] = myList[index1] + myList[index2] - index1
        index2 = index2 + 1
    print(myList[index1])
    index1 = index1 + 1

5
9
15
25
43
77
143
273
531

In [ ]:
myList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b = []
index1 = 0
index2 = 0
index1 = 1
b = myList
while(index1<10):
    myList[index1] = index1+2;
    index2 = 1;
    while(index2<index1):
        myList[index1] = b[index1]+myList[index2]-index1
        index2 = index2+1
    print(myList[index1])
    index1 = index1+1

3
5
7
9
11
13
15
17
19